#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

log "[INIT-CONFIG] Ensuring ocserv configuration file exists"

# Create default config if missing
if [ ! -f /etc/ocserv/ocserv.conf ]; then
    cp /usr/share/ocserv/ocserv.conf.template /etc/ocserv/ocserv.conf
    log "[INIT-CONFIG] Copied default config to /etc/ocserv/ocserv.conf"
fi

log "[INIT-CONFIG] ocserv configuration file is present"
