#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

echo "[SVC-OCSERV] Starting ocserv service"

exec fdmove -c 2 1 s6-setuidgid ocserv /usr/sbin/ocserv --foreground --config /etc/ocserv/ocserv.conf --log-stderr

